# Generated by Django 5.1.7 on 2025-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_entrega", models.DateTimeField(blank=True)),
                ("data_conclusao", models.DateTimeField(null=True)),
            ],
        ),
    ]
