# Generated by Django 5.1.7 on 2025-03-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="data_conclusao",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="data_criacao",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="data_entrega",
            field=models.DateField(blank=True),
        ),
    ]
