# Generated by Django 5.1.7 on 2025-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todo_data_conclusao_alter_todo_data_criacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="titulo",
            field=models.CharField(max_length=100, verbose_name="Título"),
        ),
    ]
